"""phase 4: aggregate table

Revision ID: 0a00c25cc564
Revises: 7217fad738ec
Create Date: 2026-07-21 10:47:35.372844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0a00c25cc564'
down_revision: Union[str, Sequence[str], None] = '7217fad738ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aggregate',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('org_group_id', sa.UUID(), nullable=True),
    sa.Column('respondent_n', sa.Integer(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(org_unit_id IS NOT NULL) <> (org_group_id IS NOT NULL)', name='exactly_one_target'),
    sa.ForeignKeyConstraint(['org_group_id'], ['org_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'question_id', 'org_unit_id', 'org_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aggregate')
    # ### end Alembic commands ###
