"""phase 1 schema: org_unit, org_group, person, position_type, membership

Revision ID: 244d760928da
Revises: 
Create Date: 2026-07-20 14:15:07.238577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '244d760928da'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('org_unit',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Enum('national', 'state', 'region', 'county', 'local', name='orglevel'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('fips_code', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(level = 'national') = (parent_id IS NULL)", name='national_has_no_parent'),
    sa.ForeignKeyConstraint(['parent_id'], ['org_unit.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_org_unit_parent_id', 'org_unit', ['parent_id'], unique=False)
    op.create_index('ix_org_unit_path', 'org_unit', ['path'], unique=False, postgresql_ops={'path': 'text_pattern_ops'})
    op.create_table('position_type',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('sort_order', sa.SmallInteger(), server_default='100', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('org_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('caucus', 'committee', 'issue_group', 'constituency_group', name='groupkind'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('scope_org_unit_id', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['scope_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('person',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('first_name', sa.Text(), nullable=False),
    sa.Column('last_name', sa.Text(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('home_org_unit_id', sa.UUID(), nullable=True),
    sa.Column('joined_party_on', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['home_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('membership',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('org_group_id', sa.UUID(), nullable=True),
    sa.Column('position_type_id', sa.SmallInteger(), nullable=False),
    sa.Column('start_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('(org_unit_id IS NOT NULL) <> (org_group_id IS NOT NULL)', name='exactly_one_target'),
    sa.CheckConstraint('end_date IS NULL OR end_date >= start_date', name='sane_dates'),
    sa.ForeignKeyConstraint(['org_group_id'], ['org_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_type_id'], ['position_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_membership_org_group_active', 'membership', ['org_group_id'], unique=False, postgresql_where=sa.text('end_date IS NULL'))
    op.create_index('ix_membership_org_unit_active', 'membership', ['org_unit_id'], unique=False, postgresql_where=sa.text('end_date IS NULL'))
    op.create_index('one_active_club_membership', 'membership', ['person_id', 'org_unit_id'], unique=True, postgresql_where=sa.text('end_date IS NULL AND org_unit_id IS NOT NULL'))
    op.create_index('one_active_group_membership', 'membership', ['person_id', 'org_group_id'], unique=True, postgresql_where=sa.text('end_date IS NULL AND org_group_id IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('one_active_group_membership', table_name='membership', postgresql_where=sa.text('end_date IS NULL AND org_group_id IS NOT NULL'))
    op.drop_index('one_active_club_membership', table_name='membership', postgresql_where=sa.text('end_date IS NULL AND org_unit_id IS NOT NULL'))
    op.drop_index('ix_membership_org_unit_active', table_name='membership', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_index('ix_membership_org_group_active', table_name='membership', postgresql_where=sa.text('end_date IS NULL'))
    op.drop_table('membership')
    op.drop_table('person')
    op.drop_table('org_group')
    op.drop_table('position_type')
    op.drop_index('ix_org_unit_path', table_name='org_unit', postgresql_ops={'path': 'text_pattern_ops'})
    op.drop_index('ix_org_unit_parent_id', table_name='org_unit')
    op.drop_table('org_unit')
    # ### end Alembic commands ###
    # autogenerate does not track ENUM type lifecycle - drop explicitly so
    # a downgrade followed by a re-upgrade doesn't hit "type already exists"
    postgresql.ENUM(name='groupkind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='orglevel').drop(op.get_bind(), checkfirst=True)
