"""phase 3: survey, question, response_set, answer

Revision ID: 7217fad738ec
Revises: a26bb2a4dfb1
Create Date: 2026-07-21 10:10:22.440516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7217fad738ec'
down_revision: Union[str, Sequence[str], None] = 'a26bb2a4dfb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('draft', 'open', 'closed', 'archived', name='surveystatus'), server_default='draft', nullable=False),
    sa.Column('respondent', sa.Enum('person', 'club', name='respondentkind'), server_default='person', nullable=False),
    sa.Column('target_org_unit_id', sa.UUID(), nullable=False),
    sa.Column('target_group_id', sa.UUID(), nullable=True),
    sa.Column('opens_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('closes_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('recurrence_rule', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['person.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['org_group.id'], ),
    sa.ForeignKeyConstraint(['target_org_unit_id'], ['org_unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('ordinal', sa.SmallInteger(), nullable=False),
    sa.Column('kind', sa.Enum('boolean', 'ordinal', 'single_choice', 'multi_choice', 'numeric', 'text', name='questionkind'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('help_text', sa.Text(), nullable=True),
    sa.Column('is_required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('survey_id', 'ordinal')
    )
    op.create_table('response_set',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('survey_id', sa.UUID(), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=True),
    sa.Column('org_unit_id', sa.UUID(), nullable=False),
    sa.Column('org_unit_path', sa.Text(), nullable=False),
    sa.Column('group_ids', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_complete', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['survey_id'], ['survey.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_response_set_survey_path', 'response_set', ['survey_id', 'org_unit_path'], unique=False)
    op.create_table('answer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('response_set_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_choice', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_set_id'], ['response_set.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('response_set_id', 'question_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('answer')
    op.drop_index('ix_response_set_survey_path', table_name='response_set')
    op.drop_table('response_set')
    op.drop_table('question')
    op.drop_table('survey')
    # ### end Alembic commands ###
    # autogenerate does not track ENUM type lifecycle - drop explicitly, see
    # the same fix in 244d760928da for why this matters on downgrade->upgrade
    postgresql.ENUM(name='questionkind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='respondentkind').drop(op.get_bind(), checkfirst=True)
    postgresql.ENUM(name='surveystatus').drop(op.get_bind(), checkfirst=True)
