"""phase 2: role_grant, audit_log, person auth columns

Revision ID: a26bb2a4dfb1
Revises: 244d760928da
Create Date: 2026-07-20 14:34:00.669227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a26bb2a4dfb1'
down_revision: Union[str, Sequence[str], None] = '244d760928da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('actor_person_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_person_id'], ['person.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_grant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('person_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('member', 'club_admin', 'county_admin', 'state_admin', 'national_admin', 'superuser', name='approle'), nullable=False),
    sa.Column('org_unit_id', sa.UUID(), nullable=True),
    sa.Column('org_group_id', sa.UUID(), nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("role = 'superuser' OR (org_unit_id IS NOT NULL) <> (org_group_id IS NOT NULL)", name='scoped_grant_has_exactly_one_target'),
    sa.ForeignKeyConstraint(['granted_by'], ['person.id'], ),
    sa.ForeignKeyConstraint(['org_group_id'], ['org_group.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_unit_id'], ['org_unit.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('person', sa.Column('hashed_password', sa.Text(), nullable=True))
    op.add_column('person', sa.Column('is_superuser', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('person', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'is_verified')
    op.drop_column('person', 'is_superuser')
    op.drop_column('person', 'hashed_password')
    op.drop_table('role_grant')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
    # autogenerate does not track ENUM type lifecycle - drop explicitly, see
    # the same fix in 244d760928da for why this matters on downgrade->upgrade
    postgresql.ENUM(name='approle').drop(op.get_bind(), checkfirst=True)
